### ISSUE TITLE
Browser example not working on chrome version 74.0.3729.131

### ISSUE THREAD

**Issue by ankitrgupta1** [justadudewhohacks/face-api.js#294]
Hi There,

The browser example doesn't seem to work on the Chrome browser version 74.0.3729.131.

Below is the error which I see in the console:

C:\fakepath(179,2-41): warning X3550: array reference cannot be used as an l-value; not natively addressable, forcing loop to unroll
C:\fakepath(179,2-41): error X3500: array reference cannot be used as an l-value; not natively addressable
C:\fakepath(158,7-60): error X3511: forced to unroll loop, but unrolling failed.
C:\fakepath(156,7-60): error X3511: forced to unroll loop, but unrolling failed.

Warning: D3D shader compilation failed with default flags. (ps_3_0)
 Retrying with avoid flow control
C:\fakepath(179,2-41): error X3500: array reference cannot be used as an l-value; not natively addressable
C:\fakepath(158,7-60): error X3511: forced to unroll loop, but unrolling failed.
C:\fakepath(156,7-60): error X3511: forced to unroll loop, but unrolling failed.

Warning: D3D shader compilation failed with avoid flow control flags. (ps_3_0)
 Retrying with prefer flow control
C:\fakepath(179,2-41): warning X3550: array reference cannot be used as an l-value; not natively addressable, forcing loop to unroll
C:\fakepath(179,2-41): error X3500: array reference cannot be used as an l-value; not natively addressable
C:\fakepath(158,7-60): error X3511: forced to unroll loop, but unrolling failed.
C:\fakepath(156,7-60): error X3511: forced to unroll loop, but unrolling failed.

Warning: D3D shader compilation failed with prefer flow control flags. (ps_3_0)

Failed to create D3D Shaders

Uncaught (in promise) Error: Failed to link vertex and fragment shaders.
    at linkProgram (tf-core.esm.js:17)
    at e.createProgram (tf-core.esm.js:17)
    at compileProgram (tf-core.esm.js:17)
    at tf-core.esm.js:17
    at e.getAndSaveBinary (tf-core.esm.js:17)
    at e.compileAndRun (tf-core.esm.js:17)
    at e.conv2dWithIm2Row (tf-core.esm.js:17)
    at e.conv2d (tf-core.esm.js:17)
    at ENV.engine.runKernel.x (tf-core.esm.js:17)
    at tf-core.esm.js:17

**Comment by guilhermefurtado23** [comment]
Hi,

I am with the same error I verified that this only happens and machines with little memory and old processors I carry out the tests with machines with 8GB and Processors I5 worked perfectly, however the machines 4GB and Processes Phenom II X4 or similar gave error

**Comment by emimassa** [comment]
I have intel I5 with 6GB and got same error.

**Comment by iSubhraOfficial** [comment]
getting same error, on 6GB, i3. however its working with 16gb i7.

**Comment by KNazarenko** [comment]
> Hi,
> 
> I am with the same error I verified that this only happens and machines with little memory and old processors I carry out the tests with machines with 8GB and Processors I5 worked perfectly, however the machines 4GB and Processes Phenom II X4 or similar gave error

Hi,

I have 8gb and i5 and have the same problem on the Chrome, at the same time on the browser Safari works fine.
